### ISSUE TITLE
Having trouble with PSRemoting commands for PSWindowsUpdate

### ISSUE THREAD

**Issue by aricade** [mgajda83/PSWindowsUpdate#1]
The command seems to accept and download email but not install or autoreboot.  If I run it directly from the console it does work though:

`Invoke-Command -ComputerName $Server -ScriptBlock {Install-WindowsUpdate -Install -AcceptAll -SendReport -AutoReboot  -SendHistory -ScheduleJob (get-date).AddMinutes(1) }`

The issue may be in the way I am attempting to run it? Perhaps I am missing something?  

You did an update today?  What's new?  Thanks for an awesome module you have my deepest gratitude & respect!

**Comment by mgajda83** [comment]
Hi, 
Module cant be run remote session directly. It Windows Update API limitation.
Try to use Invoke-WUJob. Cmdlet create a task in task scheduler on remote machine.

What's new? 
Nothing special, just fixed couple small bugs and typos.
