### ISSUE TITLE
Sendreport mail contains only the updates of the last server of a list of -computername

### ISSUE THREAD

**Issue by sir-Higgins** [mgajda83/PSWindowsUpdate#10]
Hello 
Good work with this module  :-)
Here is a little bug that I found.

I executed this command
get-wulist -ComputerName srv-infor-app1,int-infor-app1,dev-infor-app1 -WindowsUpdate -SendReport -PSWUSettings @{SmtpServer="smtp.xxxx.xx";From="yyy@xxx.ch";To="yyy@xxx.ch"} -Verbose

The updates are listed in the console
![image](https://github.com/mgajda83/PSWindowsUpdate/assets/24956907/43311da7-3119-44a8-9124-71aea9332ac9)

I receive the mail, but only the updates of the last server in the list are listed
 
![image](https://github.com/mgajda83/PSWindowsUpdate/assets/24956907/6b5ef437-ee3c-422d-b0e6-062894d3274d)

My configuration :

PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.3570
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3570
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> Get-Module PSWindowsUpdate

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     2.2.1.3    PSWindowsUpdate                     {Add-WUServiceManager, Enable-WURemoting, Get-WindowsUpdate, Get-W...

**Comment by mgajda83** [comment]
I confirm it was a bug. It resolved in new version.
