### ISSUE TITLE
Pswindowsupdate error

### ISSUE THREAD

**Issue by StarMusa88** [mgajda83/PSWindowsUpdate#26]
Keep getting error message when trying to use "get-windowsupdate -acceptall -install "

**Comment by callworthp** [comment]
Your problem will be impossible for anyone to help with if you do not share the error message you are getting.

**Comment by StarMusa88** [comment]
[callworthp](https://github.com/callworthp)    

get-windowsupdate -install -acceptall
Get-WindowsUpdate: Something goes wrong: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.415.40.0) - Current Channel (Broad); Object reference not set to an instance of an object.
Get-WindowsUpdate: Something goes wrong: Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.415.40.0) - Current Channel (Broad); Object reference not set to an instance of an object.

X ComputerName Result     KB          Size Title
- ------------ ------     --          ---- -----

**Comment by callworthp** [comment]
You are not alone with this error. There are other people seeing it and with a range of updates. See: https://github.com/mgajda83/PSWindowsUpdate/issues/21

**Comment by callworthp** [comment]
@StarMusa88 I'd recommend you update to the last version of PSWindowsUpdate. I installed v2.2.1.5 that just came out and every machine that previously had the "Object reference not set to an instance of an object" now works just fine.

**Comment by StarMusa88** [comment]
https://github.com/callworthp yes I will  definitely try that thanks!
